server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/PKI
    username: postgres
    password: super
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
jwt:
  secret: yL9w2T!mA7f@Q3rZ$kV1‚nX4eP9jH6bD0uS#tW8oG51C2yF7vMrE3M!p6&nb3#cl$

logging:
  level:
    org.springframework.security: DEBUG
